version: "3.8"

services:
  node1:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "5001:5000"
    networks:
      - blockchain-network

  node2:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "5002:5000"
    networks:
      - blockchain-network

networks:
  blockchain-network:
    driver: bridge
